config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :users, only: [:new, :create]

  #this will be refactored into a session management
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  get '/logout', to: 'sessions#destroy'

  get '/profile', to: 'users#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, uniqueness: true, presence: true
  validates_presence_of :password, require: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:email].downcase)

    if user && user.authenticate(params[:password])
      flash[:success] = "Welcome, #{user.email}!"
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = 'Your credentials are stinky, and that stinks.'
      render :new
    end
  end

  def destroy
    reset_session
    flash[:success] = "Logged Out!"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = user_params
    #refactor the downcase at the model level
    user[:email] = user[:email].downcase

    new_user = User.create(user)
    flash[:success] = "Welcome, #{new_user.email}!"
    session[:user_id] = new_user.id
    redirect_to root_path
  end

  def show
    @user = User.find(session[:user_id])
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anime Rater</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/users/login_form.html.erb
<%= form_with url: login_path, method: :post, local: true do |f| %>
  <%= f.label :email, 'Email:' %>
  <%= f.email_field :email %>

  <%= f.label :password, 'Password:' %>
  <%= f.password_field :password%>

  <%= f.submit 'Log In' %>
<% end %>

app/views/users/new.html.erb
<%= form_with model: @user, local: true do |f| %>
  <%= f.label :email, 'Email:' %>
  <%= f.email_field :email %>

  <%= f.label :password, 'Password:' %>
  <%= f.password_field :password%>

  <%= f.submit 'Create User' %>
<% end %>

app/views/users/show.html.erb
<h1>Hello, <%= @user.email %>!</h1>

app/views/welcome/index.html.erb
<% if current_user %>
  <%= link_to 'Log Out', logout_path %>
<% else %>
  <%= link_to 'Register as a User', new_user_path %><br>
  <%= link_to 'I Have an Account', login_path %>
<% end %>